// Shared fabric catalogue data — used by /fabric, /fabric/cotton, /fabric/polyester
// 12 fabric types we keep on hand. `comp` field is the filter key.

export type FabricType = {
  name: string;
  comp: string;
  gsm: string;
  use: string;
  fit: string;
  swatch: string;
  description: string;
};

export const fabricTypes: FabricType[] = [
  {
    name: "Polyester jersey",
    comp: "100% Polyester",
    gsm: "110–160",
    use: "T-shirts, cultural shirts, jerseys",
    fit: "★★★★★",
    swatch: "01-jersey",
    description: "Workhorse polyester for sublimation. Holds prints flat, washes clean, doesn't pill.",
  },
  {
    name: "Bird-eye mesh",
    comp: "100% Polyester",
    gsm: "135–275",
    use: "Basketball, cycling, team kits",
    fit: "★★★★★",
    swatch: "02-birdeye",
    description: "Perforated mesh — small holes for breathability, smooth face for sharp prints.",
  },
  {
    name: "Poly-spandex stretch mesh",
    comp: "92% Poly + 8% Spandex",
    gsm: "100–185",
    use: "Compression, yoga base layers",
    fit: "★★★★",
    swatch: "03-spandex",
    description: "92/8 poly-spandex. Four-way stretch for compression and fitted cuts.",
  },
  {
    name: "Polar fleece",
    comp: "100% Polyester",
    gsm: "270–420",
    use: "Hoodies, jackets, winter sports",
    fit: "★★★★",
    swatch: "04-fleece",
    description: "Heavy-knit loops, brushed both sides. Plush hand, prints through to the pile.",
  },
  {
    name: "Nylon-spandex",
    comp: "75–85% Nylon + 15–25% Spandex",
    gsm: "160–280",
    use: "Yoga, swimwear, leggings",
    fit: "★★★",
    swatch: "05-nylon",
    description: "Silky hand, excellent stretch recovery. Used for swim, yoga, fitted tops.",
  },
  {
    name: "Direct print fabric",
    comp: "100% Polyester (coated)",
    gsm: "100–170",
    use: "Flags, banners, posters, pillows",
    fit: "★★★★★",
    swatch: "06-banner",
    description: "Flag/banner fabric. Tightly woven, takes direct print on coated face.",
  },
  {
    name: "Poly-cotton blend (CVC / TC)",
    comp: "65% Poly + 35% Cotton",
    gsm: "120–260",
    use: "Polos, workwear, shirts",
    fit: "★★",
    swatch: "07-polycotton",
    description: "Poly-cotton CVC or TC. Heavier hand, used for polo and workwear.",
  },
  {
    name: "100% Cotton",
    comp: "100% Cotton",
    gsm: "180–250",
    use: "Cotton tees, hoodies — our edge",
    fit: "★",
    swatch: "08-cotton",
    description: "Pure cotton — specialty process at our factory. We dye-sub cotton via DTG/DTF for full color, soft hand.",
  },
  {
    name: "Polyester satin / chiffon",
    comp: "100% Polyester",
    gsm: "80–120",
    use: "Dresses, dance, scarves",
    fit: "★★★★★",
    swatch: "09-satin",
    description: "Polyester satin and chiffon. Silky drape, used for dance and dresses.",
  },
  {
    name: "French terry",
    comp: "100% Polyester",
    gsm: "200–320",
    use: "Hoodies, pullovers",
    fit: "★★★★",
    swatch: "10-terry",
    description: "Looped back, smooth face. Mid-weight for hoodies and pullovers.",
  },
  {
    name: "Polyester compression",
    comp: "100% Polyester",
    gsm: "180–280",
    use: "Compression wear, cycling",
    fit: "★★★★",
    swatch: "11-compression",
    description: "Polyester interlock, tight knit. Holds shape under stretch.",
  },
  {
    name: "Microfiber peach",
    comp: "100% Polyester",
    gsm: "120–200",
    use: "Blankets, pillow covers, lining",
    fit: "★★★★",
    swatch: "12-peach",
    description: "Microfiber peach skin. Soft sueded hand, used for linings and home textiles.",
  },
  // Extended polyester line — wider selection
  {
    name: "Terry cloth (looped)",
    comp: "65% Poly + 35% Cotton",
    gsm: "280–340",
    use: "Hoodies, sweatshirts, robes",
    fit: "★★★",
    swatch: "terry",
    description: "Cotton-poly terry with looped pile. Soft hand, used for hoodies and casual sweatshirts.",
  },
  {
    name: "Microfiber polyester",
    comp: "100% Polyester",
    gsm: "100–130",
    use: "Athletic tees, quick-dry",
    fit: "★★★★★",
    swatch: "microfiber",
    description: "Ultra-fine microfiber polyester. Wicks moisture, dries fast, holds photographic print detail.",
  },
  {
    name: "Pique knit",
    comp: "100% Polyester",
    gsm: "180–220",
    use: "Polo shirts, golf, sportswear",
    fit: "★★★★★",
    swatch: "pique",
    description: "Waffle-textured knit. The classic polo fabric — breathable, holds shape after wash.",
  },
  {
    name: "PBT stretch",
    comp: "100% PBT (polyester)",
    gsm: "150–180",
    use: "Swimwear, fitted athletic",
    fit: "★★★★",
    swatch: "pbt",
    description: "PBT fiber with built-in stretch and chlorine resistance. Used for competition swimwear.",
  },
  {
    name: "Interlock knit",
    comp: "100% Polyester",
    gsm: "160–220",
    use: "Activewear, fitted tees",
    fit: "★★★★★",
    swatch: "interlock",
    description: "Double-knit interlock. Smooth both sides, mid-weight, excellent drape and recovery.",
  },
  {
    name: "Pongee",
    comp: "100% Polyester",
    gsm: "60–80",
    use: "Linings, light jackets, flags",
    fit: "★★★★",
    swatch: "pongee",
    description: "Ultra-light, smooth pongee. Used as garment lining or for printed flags and banners.",
  },
  {
    name: "Rib knit 1x1",
    comp: "100% Polyester",
    gsm: "180–260",
    use: "Cuffs, collars, bodycon fits",
    fit: "★★★★",
    swatch: "rib",
    description: "Vertical rib knit. Stretchy and structured — used for trims and fitted bodycon pieces.",
  },
  {
    name: "Eyelet mesh",
    comp: "100% Polyester",
    gsm: "120–160",
    use: "Breathable layers, sportswear",
    fit: "★★★★",
    swatch: "eyelet",
    description: "Perforated eyelet mesh. Evenly distributed holes for airflow, holds print between openings.",
  },
  {
    name: "Fleece (brushed)",
    comp: "100% Polyester",
    gsm: "200–300",
    use: "Hoodies, sweatshirts, blankets",
    fit: "★★★★",
    swatch: "fleece",
    description: "Brushed-back fleece, soft and warm. Heavier hand than French terry, holds color on face.",
  },
  {
    name: "Open-hole mesh",
    comp: "100% Polyester",
    gsm: "100–150",
    use: "Linings, jerseys, vent panels",
    fit: "★★★★",
    swatch: "mesh",
    description: "Open honeycomb mesh. Maximum airflow, used in vent panels and inside jerseys.",
  },
  {
    name: "Velour",
    comp: "100% Polyester",
    gsm: "200–280",
    use: "Loungewear, tracksuits, hoodies",
    fit: "★★★★",
    swatch: "velour",
    description: "Velvet-like velour with rich pile. Plush hand, used for tracksuits and loungewear.",
  },
  {
    name: "Polyester satin",
    comp: "100% Polyester",
    gsm: "80–120",
    use: "Dresses, dancewear, linings",
    fit: "★★★★★",
    swatch: "satin",
    description: "Smooth glossy satin. Photographic print pops on the shiny face, used for performance wear.",
  },
  {
    name: "Neoprene",
    comp: "100% Polyester (neoprene)",
    gsm: "200–400",
    use: "Athletic tops, fashion pieces",
    fit: "★★★",
    swatch: "neoprene",
    description: "Thick neoprene with rubber-like body. Holds shape, used for structured athletic and fashion pieces.",
  },
  {
    name: "Polyester jersey",
    comp: "100% Polyester",
    gsm: "140–180",
    use: "Sportswear, training kits",
    fit: "★★★★★",
    swatch: "jersey",
    description: "Lightweight single-knit polyester jersey. The standard for training kits and sublimated sportswear.",
  },
  {
    name: "Plush (teddy)",
    comp: "100% Polyester",
    gsm: "200–300",
    use: "Blanket hoodies, loungewear, kids",
    fit: "★★★",
    swatch: "plush",
    description: "Dense teddy-bear plush. Super soft hand, holds dye deep, used for blanket hoodies.",
  },
  {
    name: "Acrylic",
    comp: "100% Acrylic",
    gsm: "200–400",
    use: "Sweaters, scarves, beanies",
    fit: "★★",
    swatch: "acrylic",
    description: "Wool-like acrylic. Lightweight and warm, used for sweaters, scarves, and beanies.",
  },
  {
    name: "Lurex",
    comp: "95% Polyester + 5% Lurex",
    gsm: "120–160",
    use: "Statement tees, partywear, accessories",
    fit: "★★★",
    swatch: "lurex",
    description: "Metallic-thread lurex weave. Sparkly finish for stage and partywear.",
  },
  {
    name: "Polyester lace",
    comp: "100% Polyester",
    gsm: "80–120",
    use: "Dresses, overlays, lingerie",
    fit: "★★★",
    swatch: "lace",
    description: "Polyester lace with openwork pattern. Holds shape, used for dresses and decorative overlays.",
  },
  {
    name: "Single jersey (lightweight)",
    comp: "100% Polyester",
    gsm: "120–160",
    use: "Running shirts, summer tees",
    fit: "★★★★★",
    swatch: "single-jersey",
    description: "Lightweight single jersey. Cool, breathable, the standard for running and summer tees.",
  },
  {
    name: "Double knit",
    comp: "100% Polyester",
    gsm: "220–320",
    use: "Structured tees, dresses, skirts",
    fit: "★★★★",
    swatch: "double-knit",
    description: "Dense double-knit. Heavier hand, holds structured silhouettes, used for dresses and skirts.",
  },
  {
    name: "Poly-spandex (heavy)",
    comp: "80% Polyester + 20% Spandex",
    gsm: "150–200",
    use: "Compression wear, leggings",
    fit: "★★★★★",
    swatch: "spandex",
    description: "Heavy 80/20 poly-spandex. High compression and recovery, used for leggings and base layers.",
  },
  {
    name: "Waffle knit",
    comp: "100% Polyester",
    gsm: "180–240",
    use: "Thermal layers, henleys",
    fit: "★★★★",
    swatch: "waffle",
    description: "Waffle-grid thermal knit. Texture traps warmth, used for thermal layers and henleys.",
  },
  {
    name: "Brushed polyester",
    comp: "100% Polyester",
    gsm: "180–240",
    use: "Linings, scarves, light jackets",
    fit: "★★★★",
    swatch: "brushed-poly",
    description: "Brushed poly with peach-skin feel. Soft against skin, used for linings and light scarves.",
  },
  {
    name: "Scuba",
    comp: "95% Polyester + 5% Spandex",
    gsm: "250–350",
    use: "Bodycon dresses, structured skirts",
    fit: "★★★★",
    swatch: "scuba",
    description: "Scuba-knit with body and recovery. Smooth face, used for bodycon dresses and structured skirts.",
  },
  {
    name: "Performance mesh",
    comp: "100% Polyester",
    gsm: "120–160",
    use: "Athletic jerseys, training tops",
    fit: "★★★★★",
    swatch: "performance-mesh",
    description: "Engineered athletic mesh. Tiny perforations for ventilation, holds print between holes.",
  },
  {
    name: "Polar fleece (anti-pill)",
    comp: "100% Polyester",
    gsm: "220–320",
    use: "Hoodies, jackets, blankets",
    fit: "★★★★",
    swatch: "polar-anti-pill",
    description: "Anti-pill polar fleece. Surface resists pilling after repeated washing, holds color well.",
  },
  {
    name: "Mesh net (athletic)",
    comp: "100% Polyester",
    gsm: "60–100",
    use: "Jersey numbers, vent panels",
    fit: "★★★",
    swatch: "mesh-net",
    description: "Open athletic mesh. Used for jersey numbers, side panels, and breathable vent inserts.",
  },
  {
    name: "Stretch lace",
    comp: "90% Polyester + 10% Spandex",
    gsm: "100–140",
    use: "Dancewear, fitted overlays, lingerie",
    fit: "★★★",
    swatch: "stretch-lace",
    description: "Stretch lace with spandex. Conforms to body, used for dancewear and fitted overlays.",
  },
];

// Filter helpers
export const cottonFabrics = fabricTypes.filter((f) =>
  f.comp.toLowerCase().includes("cotton"),
);
export const polyesterFabrics = fabricTypes.filter(
  (f) =>
    f.comp.toLowerCase().includes("poly") &&
    !f.comp.toLowerCase().includes("cotton"),
);
