export type Product = {
  name: string;
  slug: string;
  plate: string;
  process: string;
  sku: string;
  spu: string;
  url: string;
  fabricCount: number;
  mainCategory: string;
  mainCategoryLabel: string;
  subcategories: string[];
  subcategorySlugs: string[];
  description: string;
  tags: string[];
};

export const productMainCategories = [
  { id: "apparel", label: "Apparel" },
  { id: "home", label: "Home & Living" },
  { id: "accessories", label: "Bags & Accessories" },
  { id: "flags", label: "Flags & Banners" },
  { id: "hardgoods", label: "Hard Goods & Lifestyle" },
  { id: "custom", label: "Custom Projects" },
];

export const productSubcategories: Record<string, { label: string; mainCategory: string }> = {
  "t-shirts": { label: "T-Shirts", mainCategory: "apparel" },
  "hoodies-sweatshirts": { label: "Hoodies & Sweatshirts", mainCategory: "apparel" },
  "jerseys-singlets": { label: "Jerseys & Singlets", mainCategory: "apparel" },
  "racing-kits": { label: "Racing Kits", mainCategory: "apparel" },
  "cycling-kits": { label: "Cycling Kits", mainCategory: "apparel" },
  "golf-bowling-shirts": { label: "Golf / Bowling Shirts", mainCategory: "apparel" },
  "pants-shorts": { label: "Pants & Shorts", mainCategory: "apparel" },
  "vests": { label: "Vests", mainCategory: "apparel" },
  "other-apparel": { label: "Other Apparel", mainCategory: "apparel" },
  "throw-pillows": { label: "Throw Pillows", mainCategory: "home" },
  "cushion-covers": { label: "Cushion Covers", mainCategory: "home" },
  "blankets-throws": { label: "Blankets & Throws", mainCategory: "home" },
  "curtains-drapes": { label: "Curtains & Drapes", mainCategory: "home" },
  "tablecloths": { label: "Tablecloths", mainCategory: "home" },
  "towels": { label: "Towels", mainCategory: "home" },
  "bedding-sets": { label: "Bedding Sets", mainCategory: "home" },
  "drawstring-bags": { label: "Drawstring Bags", mainCategory: "accessories" },
  "backpacks": { label: "Backpacks", mainCategory: "accessories" },
  "tote-bags": { label: "Tote Bags", mainCategory: "accessories" },
  "baseball-caps": { label: "Baseball Caps", mainCategory: "accessories" },
  "bucket-hats": { label: "Bucket Hats", mainCategory: "accessories" },
  "scarves-bandanas": { label: "Scarves & Bandanas", mainCategory: "accessories" },
  "lanyards": { label: "Lanyards", mainCategory: "accessories" },
  "aprons": { label: "Aprons", mainCategory: "accessories" },
  "garden-flags": { label: "Garden Flags", mainCategory: "flags" },
  "beach-flags": { label: "Beach Flags", mainCategory: "flags" },
  "hand-flags": { label: "Hand Flags", mainCategory: "flags" },
  "trade-show-banners": { label: "Trade Show Banners", mainCategory: "flags" },
  "pull-up-banners": { label: "Pull-Up Banners", mainCategory: "flags" },
  "pennant-strings": { label: "Pennant Strings", mainCategory: "flags" },
  "flags-banners": { label: "Flags & Banners", mainCategory: "flags" },
  "mouse-pads": { label: "Mouse Pads", mainCategory: "hardgoods" },
  "coasters": { label: "Coasters", mainCategory: "hardgoods" },
  "puzzles": { label: "Puzzles", mainCategory: "hardgoods" },
  "phone-cases": { label: "Phone Cases", mainCategory: "hardgoods" },
  "airpods-cases": { label: "AirPods Cases", mainCategory: "hardgoods" },
  "mugs": { label: "Mugs (wrap print)", mainCategory: "hardgoods" },
  "keychains": { label: "Keychains", mainCategory: "hardgoods" },
  "magnets": { label: "Magnets", mainCategory: "hardgoods" },
  "pet-apparel": { label: "Pet Apparel", mainCategory: "custom" },
  "shoe-uppers": { label: "Shoe Uppers", mainCategory: "custom" },
  "lampshades": { label: "Lampshades", mainCategory: "custom" },
  "wall-art": { label: "Wall Art", mainCategory: "custom" },
  "festival-costumes": { label: "Festival Costumes", mainCategory: "custom" },
  "theatre-costumes": { label: "Theatre Costumes", mainCategory: "custom" },
  "promotional-items": { label: "Promotional Items", mainCategory: "custom" },
  "custom-other": { label: "Anything else you imagine", mainCategory: "custom" },
};

export const productTypes: Product[] = [
  {
    name: "CrossFit Wear",
    slug: "crossfit-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom crossfit wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Table Tennis Outfit",
    slug: "table-tennis-outfit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom table tennis outfit — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Transit & Transport Wear",
    slug: "transit-and-transport-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom transit & transport wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Transit & Transport Wear可定制",
    slug: "transit-and-transport-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom transit & transport wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Corporate & Promo Wear",
    slug: "corporate-and-promo-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Promotional Items"],
    subcategorySlugs: ["promotional-items"],
    description: "Custom corporate & promo wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "promotional-items", "custom-project", "polyester"],
  },
  {
    name: "Corporate & Promo Wear可定制",
    slug: "corporate-and-promo-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Promotional Items"],
    subcategorySlugs: ["promotional-items"],
    description: "Custom corporate & promo wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "promotional-items", "custom-project", "polyester"],
  },
  {
    name: "Bowling Shirt",
    slug: "bowling-shirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Golf / Bowling Shirts"],
    subcategorySlugs: ["golf-bowling-shirts"],
    description: "Custom bowling shirt — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "golf-bowling-shirts", "apparel", "polyester"],
  },
  {
    name: "Gym Wear",
    slug: "gym-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom gym wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Hockey Jersey",
    slug: "hockey-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "12",
    spu: "3MTXLB56",
    url: "https://www.yoycol.com/product_detail/3MTXLB56/All-Over-Print-MenS-Half-Zip-Pullover-Sweatshirt",
    fabricCount: 2,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom hockey jersey — premium sublimation print, MOQ 50 pcs. 12 active SKUs. Available in 2 fabric options.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Surf Wear",
    slug: "surf-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom surf wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Medical & Healthcare Wear",
    slug: "medical-and-healthcare-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 15,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom medical & healthcare wear — premium sublimation print, MOQ 50 pcs. Available in 15 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Medical & Healthcare Wear可定制",
    slug: "medical-and-healthcare-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 15,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom medical & healthcare wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 15 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Snowboard Wear",
    slug: "snowboard-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom snowboard wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Cheer Wear",
    slug: "cheer-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom cheer wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Softball Jersey",
    slug: "softball-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom softball jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Security Wear",
    slug: "security-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom security wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Security Wear可定制",
    slug: "security-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom security wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Construction Wear",
    slug: "construction-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom construction wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Construction Wear可定制",
    slug: "construction-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom construction wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Express & Logistics Wear",
    slug: "express-and-logistics-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom express & logistics wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Express & Logistics Wear可定制",
    slug: "express-and-logistics-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom express & logistics wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Boxing Gear",
    slug: "boxing-gear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom boxing gear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Volleyball Jersey",
    slug: "volleyball-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom volleyball jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Wrestling Gear",
    slug: "wrestling-gear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom wrestling gear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "School & Education Wear",
    slug: "school-and-education-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Pet Apparel"],
    subcategorySlugs: ["pet-apparel"],
    description: "Custom school & education wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "pet-apparel", "custom-project", "polyester"],
  },
  {
    name: "School & Education Wear可定制",
    slug: "school-and-education-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Pet Apparel"],
    subcategorySlugs: ["pet-apparel"],
    description: "Custom school & education wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "pet-apparel", "custom-project", "polyester"],
  },
  {
    name: "Pilates Wear",
    slug: "pilates-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom pilates wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Activewear",
    slug: "activewear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "3",
    spu: "3MPHTU08",
    url: "https://www.yoycol.com/product_detail/3MPHTU08/All-Over-Print-Mens-long-Sleeve-T-Shirt-With-Dropped-Shoulders-Interlock",
    fabricCount: 3,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom activewear — premium sublimation print, MOQ 50 pcs. 3 active SKUs. Available in 3 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Baby Bodysuit",
    slug: "baby-bodysuit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "4",
    spu: "2KBBMB01",
    url: "https://www.yoycol.com/product_detail/2KBBMB01/Baby-Short-Sleeve-Onesie-Printed-in-USA-190GSM-Front-DTF",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom baby bodysuit — premium sublimation print, MOQ 50 pcs. 4 active SKUs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "kids", "polyester"],
  },
  {
    name: "Bodysuit",
    slug: "bodysuit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "12",
    spu: "3WJMBX16",
    url: "https://www.yoycol.com/product_detail/3WJMBX16/All-Over-Print-Womens-Tank-Bodysuit",
    fabricCount: 1,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom bodysuit — premium sublimation print, MOQ 50 pcs. 12 active SKUs. Available in 1 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Coord Set",
    slug: "coord-set",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "34",
    spu: "3KCSZJ10",
    url: "https://www.yoycol.com/product_detail/3KCSZJ10/The-Plamix-All-Over-Print-Childrens-Shirt-With-Pocket-140GSM-Slub-Cotton",
    fabricCount: 4,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom coord set — premium sublimation print, MOQ 50 pcs. 34 active SKUs. Available in 4 fabric options.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Dress",
    slug: "dress",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "50",
    spu: "3WBXGZ50",
    url: "https://www.yoycol.com/product_detail/3WBXGZ50/All-Over-Print-Womens-Tank-Vest-Dress",
    fabricCount: 4,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom dress — premium sublimation print, MOQ 50 pcs. 50 active SKUs. Available in 4 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Hoodie",
    slug: "hoodie",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "397",
    spu: "2AHAYR15",
    url: "https://www.yoycol.com/product_detail/2AHAYR15/All-Over-Print-Womens-Rectangle-Scarf-170X45cm",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Hoodies & Sweatshirts"],
    subcategorySlugs: ["hoodies-sweatshirts"],
    description: "Custom hoodie — premium sublimation print, MOQ 50 pcs. 397 active SKUs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "hoodies-sweatshirts", "apparel", "polyester"],
  },
  {
    name: "Jacket",
    slug: "jacket",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "84",
    spu: "2MHPJR90",
    url: "https://www.yoycol.com/product_detail/2MHPJR90/Mens-Fleece-Lined-Vintage-Wash-Zip-Hoodie-360GSM-DTF",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom jacket — premium sublimation print, MOQ 50 pcs. 84 active SKUs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Kids Sportswear",
    slug: "kids-sportswear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "4",
    spu: "3KCSSY02",
    url: "https://www.yoycol.com/product_detail/3KCSSY02/All-Over-Print-Kids-Baseball-Jersey",
    fabricCount: 2,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom kids sportswear — premium sublimation print, MOQ 50 pcs. 4 active SKUs. Available in 2 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "kids", "polyester"],
  },
  {
    name: "Knitwear",
    slug: "knitwear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "26",
    spu: "2MHPHR99",
    url: "https://www.yoycol.com/product_detail/2MHPHR99/Mens-Vintage-Crewneck-Knit-Sweater-285GSM-DTG",
    fabricCount: 5,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom knitwear — premium sublimation print, MOQ 50 pcs. 26 active SKUs. Available in 5 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Pants",
    slug: "pants",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "114",
    spu: "1WPXZY10",
    url: "https://www.yoycol.com/product_detail/1WPXZY10/All-Over-Print-Womens-High-Stretch-Tights",
    fabricCount: 13,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Pants & Shorts"],
    subcategorySlugs: ["pants-shorts"],
    description: "Custom pants — premium sublimation print, MOQ 50 pcs. 114 active SKUs. Available in 13 fabric options.",
    tags: ["sublimation", "all-over-print", "pants-shorts", "apparel", "polyester"],
  },
  {
    name: "Polo Shirt",
    slug: "polo-shirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "9",
    spu: "3KTXPL29",
    url: "https://www.yoycol.com/product_detail/3KTXPL29/All-Over-Print-Childrens-Lapel-Polo-Shirt-145GSM-Birdseye",
    fabricCount: 3,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom polo shirt — premium sublimation print, MOQ 50 pcs. 9 active SKUs. Available in 3 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Romper & Jumpsuit",
    slug: "romper-and-jumpsuit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "19",
    spu: "3MJMJH01",
    url: "https://www.yoycol.com/product_detail/3MJMJH01/All-Over-Print-Unisex-Thickened-Home-Jumpsuit",
    fabricCount: 4,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom romper & jumpsuit — premium sublimation print, MOQ 50 pcs. 19 active SKUs. Available in 4 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Shirt",
    slug: "shirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "103",
    spu: "2MHPDM39",
    url: "https://www.yoycol.com/product_detail/2MHPDM39/Unisex-Durable-Pullover-Sweatshirt-290GSM-DTG",
    fabricCount: 12,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom shirt — premium sublimation print, MOQ 50 pcs. 103 active SKUs. Available in 12 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Skirt",
    slug: "skirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "16",
    spu: "3CDDAQ01",
    url: "https://www.yoycol.com/product_detail/3CDDAQ01/All-Over-Print-Kids-Short-Sleeve-Dress",
    fabricCount: 2,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Pants & Shorts"],
    subcategorySlugs: ["pants-shorts"],
    description: "Custom skirt — premium sublimation print, MOQ 50 pcs. 16 active SKUs. Available in 2 fabric options.",
    tags: ["sublimation", "all-over-print", "pants-shorts", "apparel", "polyester"],
  },
  {
    name: "Sleepwear & Underwear",
    slug: "sleepwear-and-underwear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "62",
    spu: "2WUSMG97",
    url: "https://www.yoycol.com/product_detail/2WUSMG97/Womens-Seamless-Briefs-Printed-in-USA-180GSM-DTF",
    fabricCount: 10,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom sleepwear & underwear — premium sublimation print, MOQ 50 pcs. 62 active SKUs. Available in 10 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Sports Top",
    slug: "sports-top",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "7",
    spu: "3AHGYD02",
    url: "https://www.yoycol.com/product_detail/3AHGYD02/Sports-Square-Towel",
    fabricCount: 3,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom sports top — premium sublimation print, MOQ 50 pcs. 7 active SKUs. Available in 3 fabric options.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Sweatshirt",
    slug: "sweatshirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "34",
    spu: "2MHPSA03",
    url: "https://www.yoycol.com/product_detail/2MHPSA03/Mens-Distressed-Vintage-Wash-Sweatshirt-360GSM-DTG",
    fabricCount: 5,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["T-Shirts", "Hoodies & Sweatshirts"],
    subcategorySlugs: ["t-shirts", "hoodies-sweatshirts"],
    description: "Custom sweatshirt — premium sublimation print, MOQ 50 pcs. 34 active SKUs. Available in 5 fabric options.",
    tags: ["sublimation", "all-over-print", "t-shirts", "apparel", "hoodies-sweatshirts", "polyester"],
  },
  {
    name: "T-Shirt",
    slug: "t-shirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "135",
    spu: "2KTXDM69",
    url: "https://www.yoycol.com/product_detail/2KTXDM69/Childrens-T-Shirts-Printed-in-USA-Gildan-64000B-DTG",
    fabricCount: 14,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["T-Shirts"],
    subcategorySlugs: ["t-shirts"],
    description: "Custom t-shirt — premium sublimation print, MOQ 50 pcs. 135 active SKUs. Available in 14 fabric options.",
    tags: ["sublimation", "all-over-print", "t-shirts", "apparel", "polyester"],
  },
  {
    name: "Tank Top & Camis",
    slug: "tank-top-and-camis",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "61",
    spu: "2MBXMA09",
    url: "https://www.yoycol.com/product_detail/2MBXMA09/Mens-Loose-Sleeveless-Hoodie-320GSM-DTF",
    fabricCount: 7,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["T-Shirts"],
    subcategorySlugs: ["t-shirts"],
    description: "Custom tank top & camis — premium sublimation print, MOQ 50 pcs. 61 active SKUs. Available in 7 fabric options.",
    tags: ["sublimation", "all-over-print", "t-shirts", "apparel", "polyester"],
  },
  {
    name: "Winter Wear",
    slug: "winter-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "4",
    spu: "3MHZDM41",
    url: "https://www.yoycol.com/product_detail/3MHZDM41/All-Over-Print-Mens-Half-Zip-Pullover",
    fabricCount: 3,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom winter wear — premium sublimation print, MOQ 50 pcs. 4 active SKUs. Available in 3 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Cricket Outfit",
    slug: "cricket-outfit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom cricket outfit — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Baseball Jersey",
    slug: "baseball-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "8",
    spu: "2AMSMG90",
    url: "https://www.yoycol.com/product_detail/2AMSMG90/Adult-Solid-Color-Mesh-Baseball-Cap-Printed-in-USA",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom baseball jersey — premium sublimation print, MOQ 50 pcs. 8 active SKUs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Rugby Jersey",
    slug: "rugby-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom rugby jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Martial Arts Gear",
    slug: "martial-arts-gear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom martial arts gear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Beach Sports",
    slug: "beach-sports",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "4",
    spu: "2HBTSJ19",
    url: "https://www.yoycol.com/product_detail/2HBTSJ19/Adult-Beach-Towel-Printed-in-Canada-320GSM",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom beach sports — premium sublimation print, MOQ 50 pcs. 4 active SKUs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Swimwear",
    slug: "swimwear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "28",
    spu: "3KYYOP05",
    url: "https://www.yoycol.com/product_detail/3KYYOP05/All-Over-Print-Girls-Sleeveless-One-Piece-Swimsuit",
    fabricCount: 1,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom swimwear — premium sublimation print, MOQ 50 pcs. 28 active SKUs. Available in 1 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Skating Wear",
    slug: "skating-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom skating wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Skate Wear",
    slug: "skate-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom skate wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Ski Wear",
    slug: "ski-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom ski wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Dive Wear",
    slug: "dive-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom dive wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "AFL Jersey",
    slug: "afl-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom afl jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Yoga Wear",
    slug: "yoga-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "26",
    spu: "3CP",
    url: "https://www.yoycol.com/product_detail/3CP/All-Over-Print-Casual-Leggings",
    fabricCount: 2,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom yoga wear — premium sublimation print, MOQ 50 pcs. 26 active SKUs. Available in 2 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Athletics Wear",
    slug: "athletics-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom athletics wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Esports Jersey",
    slug: "esports-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom esports jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Basketball Jersey",
    slug: "basketball-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "11",
    spu: "3MBXVL01",
    url: "https://www.yoycol.com/product_detail/3MBXVL01/All-Over-Print-Mens-V-neck-Tank-Top",
    fabricCount: 1,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom basketball jersey — premium sublimation print, MOQ 50 pcs. 11 active SKUs. Available in 1 fabric options.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Netball Jersey",
    slug: "netball-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom netball jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "MMA Gear",
    slug: "mma-gear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom mma gear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Tennis Outfit",
    slug: "tennis-outfit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom tennis outfit — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Football Jersey",
    slug: "football-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom football jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Badminton Outfit",
    slug: "badminton-outfit",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "6",
    spu: "3MBXGT28",
    url: "https://www.yoycol.com/product_detail/3MBXGT28/All-Over-Print-Mens-O-neck-Tank-Top-210GSM",
    fabricCount: 3,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom badminton outfit — premium sublimation print, MOQ 50 pcs. 6 active SKUs. Available in 3 fabric options.",
    tags: ["sublimation", "all-over-print", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Dance Wear",
    slug: "dance-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom dance wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Soccer Jersey",
    slug: "soccer-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "8",
    spu: "3MPXDK57",
    url: "https://www.yoycol.com/product_detail/3MPXDK57/All-Over-Print-Mens-Pocket-Customizable-Shorts",
    fabricCount: 3,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom soccer jersey — premium sublimation print, MOQ 50 pcs. 8 active SKUs. Available in 3 fabric options.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Running Wear",
    slug: "running-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "14",
    spu: "3MBXGT27",
    url: "https://www.yoycol.com/product_detail/3MBXGT27/All-Over-Print-Mens-Sports-Vest",
    fabricCount: 2,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom running wear — premium sublimation print, MOQ 50 pcs. 14 active SKUs. Available in 2 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Fishing Shirt",
    slug: "fishing-shirt",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom fishing shirt — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Triathlon Wear",
    slug: "triathlon-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom triathlon wear — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Lacrosse Jersey",
    slug: "lacrosse-jersey",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Jerseys & Singlets"],
    subcategorySlugs: ["jerseys-singlets"],
    description: "Custom lacrosse jersey — premium sublimation print, MOQ 50 pcs.",
    tags: ["sublimation", "all-over-print", "jerseys-singlets", "apparel", "polyester"],
  },
  {
    name: "Retail Wear",
    slug: "retail-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom retail wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Retail Wear可定制",
    slug: "retail-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom retail wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Hospitality & F&B Wear",
    slug: "hospitality-and-fandb-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom hospitality & f&b wear — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Hospitality & F&B Wear可定制",
    slug: "hospitality-and-fandb-wear可定制",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Other Apparel"],
    subcategorySlugs: ["other-apparel"],
    description: "Custom hospitality & f&b wear可定制 — premium sublimation print, MOQ 50 pcs. Available in 16 fabric options.",
    tags: ["sublimation", "all-over-print", "other-apparel", "apparel", "polyester"],
  },
  {
    name: "Cycling Wear",
    slug: "cycling-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "12",
    spu: "3MTXUB79",
    url: "https://www.yoycol.com/product_detail/3MTXUB79/All-Over-Print-Mens-Sun-Protection-Hooded-Sport-Top",
    fabricCount: 2,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Cycling Kits"],
    subcategorySlugs: ["cycling-kits"],
    description: "Custom cycling wear — premium sublimation print, MOQ 50 pcs. 12 active SKUs. Available in 2 fabric options.",
    tags: ["sublimation", "all-over-print", "cycling-kits", "apparel", "polyester"],
  },
  {
    name: "Golf Wear",
    slug: "golf-wear",
    plate: "All-Over Print",
    process: "Sublimation",
    sku: "47",
    spu: "3KCSFH01",
    url: "https://www.yoycol.com/product_detail/3KCSFH01/All-Over-Print-Teenage-Polo-Collar-Jersey",
    fabricCount: 8,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Golf / Bowling Shirts"],
    subcategorySlugs: ["golf-bowling-shirts"],
    description: "Custom golf wear — premium sublimation print, MOQ 50 pcs. 47 active SKUs. Available in 8 fabric options.",
    tags: ["sublimation", "all-over-print", "golf-bowling-shirts", "apparel", "polyester"],
  },
  {
    name: "Baby Bodysuit",
    slug: "blank-baby-bodysuit",
    plate: "Blank",
    process: "DTF",
    sku: "3",
    spu: "2KBBMB01",
    url: "https://www.yoycol.com/product_detail/2KBBMB01/Baby-Short-Sleeve-Onesie-Printed-in-USA-190GSM-Front-DTF",
    fabricCount: 2,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom baby bodysuit — premium sublimation print, MOQ 50 pcs. 3 active SKUs. Available in 2 fabric options.",
    tags: ["dtf", "blank", "custom-other", "custom-project", "kids", "cotton"],
  },
  {
    name: "Hoodie",
    slug: "blank-hoodie",
    plate: "Blank",
    process: "DTF",
    sku: "4",
    spu: "2MHPDM73",
    url: "https://www.yoycol.com/product_detail/2MHPDM73/Unisex-Pullover-Hoodie-with-Micro-Fleece-Lining-DTF",
    fabricCount: 16,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Hoodies & Sweatshirts"],
    subcategorySlugs: ["hoodies-sweatshirts"],
    description: "Custom hoodie — premium sublimation print, MOQ 50 pcs. 4 active SKUs. Available in 16 fabric options.",
    tags: ["dtf", "blank", "hoodies-sweatshirts", "apparel", "cotton"],
  },
  {
    name: "Pants",
    slug: "blank-pants",
    plate: "Blank",
    process: "DTF",
    sku: "1",
    spu: "2MPXMB02",
    url: "https://www.yoycol.com/product_detail/2MPXMB02/Mens-Casual-Shorts-Printed-in-USA-290GSM-Front-DTF",
    fabricCount: 6,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["Pants & Shorts"],
    subcategorySlugs: ["pants-shorts"],
    description: "Custom pants — premium sublimation print, MOQ 50 pcs. 1 active SKUs. Available in 6 fabric options.",
    tags: ["dtf", "blank", "pants-shorts", "apparel", "cotton"],
  },
  {
    name: "Set",
    slug: "blank-set",
    plate: "Blank",
    process: "DTF",
    sku: "1",
    spu: "3WSTLL37",
    url: "https://www.yoycol.com/product_detail/3WSTLL37/Womens-Tracksuit-With-Fleece-DTF",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom set — premium sublimation print, MOQ 50 pcs. 1 active SKUs.",
    tags: ["dtf", "blank", "custom-other", "custom-project", "cotton"],
  },
  {
    name: "Shirt",
    slug: "blank-shirt",
    plate: "Blank",
    process: "DTF/DTG",
    sku: "12",
    spu: "2MTXMB06",
    url: "https://www.yoycol.com/product_detail/2MTXMB06/Mens-Long-Sleeve-T-Shirt-Printed-in-USA-180GSM-Double-DTF",
    fabricCount: 10,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom shirt — premium sublimation print, MOQ 50 pcs. 12 active SKUs. Available in 10 fabric options.",
    tags: ["dtf", "dtg", "blank", "custom-other", "custom-project", "cotton"],
  },
  {
    name: "Sweatshirt",
    slug: "blank-sweatshirt",
    plate: "Blank",
    process: "DTF",
    sku: "5",
    spu: "2MWYYL01",
    url: "https://www.yoycol.com/product_detail/2MWYYL01/Versatile-Mens-Polyester-Fleece-Sweatshirt-DTF",
    fabricCount: 5,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["T-Shirts", "Hoodies & Sweatshirts"],
    subcategorySlugs: ["t-shirts", "hoodies-sweatshirts"],
    description: "Custom sweatshirt — premium sublimation print, MOQ 50 pcs. 5 active SKUs. Available in 5 fabric options.",
    tags: ["dtf", "blank", "t-shirts", "apparel", "hoodies-sweatshirts", "cotton"],
  },
  {
    name: "T-Shirt",
    slug: "blank-t-shirt",
    plate: "Blank",
    process: "DTF/DTG",
    sku: "13",
    spu: "2KTXMD71",
    url: "https://www.yoycol.com/product_detail/2KTXMD71/Youth-T-shirt-Printed-in-USA-180GSM-Front-Back-DTF",
    fabricCount: 10,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["T-Shirts"],
    subcategorySlugs: ["t-shirts"],
    description: "Custom t-shirt — premium sublimation print, MOQ 50 pcs. 13 active SKUs. Available in 10 fabric options.",
    tags: ["dtf", "dtg", "blank", "t-shirts", "apparel", "cotton"],
  },
  {
    name: "Tank Top",
    slug: "blank-tank-top",
    plate: "Blank",
    process: "DTF",
    sku: "3",
    spu: "2MBXMD71",
    url: "https://www.yoycol.com/product_detail/2MBXMD71/Washed-Cotton-Sleeveless-T-Shirt-Printed-in-USA-210GSM-Cotton-Double-sided-DTF",
    fabricCount: 0,
    mainCategory: "apparel",
    mainCategoryLabel: "Apparel",
    subcategories: ["T-Shirts"],
    subcategorySlugs: ["t-shirts"],
    description: "Custom tank top — premium sublimation print, MOQ 50 pcs. 3 active SKUs.",
    tags: ["dtf", "blank", "t-shirts", "apparel", "cotton"],
  },
  {
    name: "Polo Shirt",
    slug: "blank-polo-shirt",
    plate: "Blank",
    process: "DTF/DTG",
    sku: "6",
    spu: "2MTXCM57",
    url: "https://www.yoycol.com/product_detail/2MTXCM57/Adult-Polo-Jersey-Sport-Shirt-Printed-in-USA-Gildan8800-DTF-Front",
    fabricCount: 3,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom polo shirt — premium sublimation print, MOQ 50 pcs. 6 active SKUs. Available in 3 fabric options.",
    tags: ["dtf", "dtg", "blank", "custom-other", "custom-project", "cotton"],
  },
  {
    name: "Blanket & Bedding",
    slug: "home-blanket-and-bedding",
    plate: "Home & Living",
    process: "Sublimation",
    sku: "31",
    spu: "2AAOWO9",
    url: "https://www.yoycol.com/product_detail/2AAOWO9/Personalized-Plush-Hug-Doll-Pillow",
    fabricCount: 0,
    mainCategory: "home",
    mainCategoryLabel: "Home & Living",
    subcategories: ["Blankets & Throws", "Bedding Sets"],
    subcategorySlugs: ["blankets-throws", "bedding-sets"],
    description: "Custom blanket & bedding — premium sublimation print, MOQ 50 pcs. 31 active SKUs.",
    tags: ["sublimation", "home-living", "blankets-throws", "home", "bedding-sets", "polyester"],
  },
  {
    name: "Desk & Stationery",
    slug: "home-desk-and-stationery",
    plate: "Home & Living",
    process: "Sublimation",
    sku: "5",
    spu: "2HKKZB08",
    url: "https://www.yoycol.com/product_detail/2HKKZB08/Single-Sided-Printed-Prayer-Journal",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom desk & stationery — premium sublimation print, MOQ 50 pcs. 5 active SKUs.",
    tags: ["sublimation", "home-living", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Kitchen & Apron",
    slug: "home-kitchen-and-apron",
    plate: "Home & Living",
    process: "Sublimation",
    sku: "7",
    spu: "2HKAWQ05",
    url: "https://www.yoycol.com/product_detail/2HKAWQ05/Adjustable-Apron-With-White-Strap",
    fabricCount: 0,
    mainCategory: "accessories",
    mainCategoryLabel: "Bags & Accessories",
    subcategories: ["Aprons"],
    subcategorySlugs: ["aprons"],
    description: "Custom kitchen & apron — premium sublimation print, MOQ 50 pcs. 7 active SKUs.",
    tags: ["sublimation", "home-living", "aprons", "accessory", "polyester"],
  },
  {
    name: "Outdoor & Garden",
    slug: "home-outdoor-and-garden",
    plate: "Home & Living",
    process: "Sublimation",
    sku: "39",
    spu: "2AAOFT01",
    url: "https://www.yoycol.com/product_detail/2AAOFT01/Halloween-Windsock",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom outdoor & garden — premium sublimation print, MOQ 50 pcs. 39 active SKUs.",
    tags: ["sublimation", "home-living", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Towel",
    slug: "home-towel",
    plate: "Home & Living",
    process: "Sublimation",
    sku: "14",
    spu: "2HBTSJ19",
    url: "https://www.yoycol.com/product_detail/2HBTSJ19/Adult-Beach-Towel-Printed-in-Canada-320GSM",
    fabricCount: 0,
    mainCategory: "home",
    mainCategoryLabel: "Home & Living",
    subcategories: ["Towels"],
    subcategorySlugs: ["towels"],
    description: "Custom towel — premium sublimation print, MOQ 50 pcs. 14 active SKUs.",
    tags: ["sublimation", "home-living", "towels", "home", "polyester"],
  },
  {
    name: "Wall Art",
    slug: "home-wall-art",
    plate: "Home & Living",
    process: "Sublimation",
    sku: "64",
    spu: "1PCP",
    url: "https://www.yoycol.com/product_detail/1PCP/Frameless-Single-Mural",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Wall Art"],
    subcategorySlugs: ["wall-art"],
    description: "Custom wall art — premium sublimation print, MOQ 50 pcs. 64 active SKUs.",
    tags: ["sublimation", "home-living", "wall-art", "custom-project", "polyester"],
  },
  {
    name: "Bag",
    slug: "accessories-bag",
    plate: "Accessories",
    process: "Sublimation",
    sku: "49",
    spu: "2ABBDJ69",
    url: "https://www.yoycol.com/product_detail/2ABBDJ69/Minimalist-Square-Crossbody-Bucket-Bag",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom bag — premium sublimation print, MOQ 50 pcs. 49 active SKUs.",
    tags: ["sublimation", "accessories", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Car Accessories",
    slug: "accessories-car-accessories",
    plate: "Accessories",
    process: "Sublimation",
    sku: "12",
    spu: "2AAOMG70",
    url: "https://www.yoycol.com/product_detail/2AAOMG70/Car-Aluminum-License-Plate-Printed-in-USA",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom car accessories — premium sublimation print, MOQ 50 pcs. 12 active SKUs.",
    tags: ["sublimation", "accessories", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Face Mask",
    slug: "accessories-face-mask",
    plate: "Accessories",
    process: "Sublimation",
    sku: "3",
    spu: "320KZ",
    url: "https://www.yoycol.com/product_detail/320KZ/All-Over-Print-Face-Mask-with-Adjustable-Ear-Loops",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom face mask — premium sublimation print, MOQ 50 pcs. 3 active SKUs.",
    tags: ["sublimation", "accessories", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Hat & Cap",
    slug: "accessories-hat-and-cap",
    plate: "Accessories",
    process: "Sublimation",
    sku: "36",
    spu: "2AAOYF03",
    url: "https://www.yoycol.com/product_detail/2AAOYF03/Bucket-Hat",
    fabricCount: 0,
    mainCategory: "accessories",
    mainCategoryLabel: "Bags & Accessories",
    subcategories: ["Baseball Caps"],
    subcategorySlugs: ["baseball-caps"],
    description: "Custom hat & cap — premium sublimation print, MOQ 50 pcs. 36 active SKUs.",
    tags: ["sublimation", "accessories", "baseball-caps", "accessory", "polyester"],
  },
  {
    name: "Jewelry",
    slug: "accessories-jewelry",
    plate: "Accessories",
    process: "Sublimation",
    sku: "3",
    spu: "2AJBSS05",
    url: "https://www.yoycol.com/product_detail/2AJBSS05/Mens-Fashion-Belt",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom jewelry — premium sublimation print, MOQ 50 pcs. 3 active SKUs.",
    tags: ["sublimation", "accessories", "custom-other", "custom-project", "polyester"],
  },
  {
    name: "Pet Supplies",
    slug: "accessories-pet-supplies",
    plate: "Accessories",
    process: "Sublimation",
    sku: "10",
    spu: "3AHPDG01",
    url: "https://www.yoycol.com/product_detail/3AHPDG01/All-Over-Print-Hooded-Sweatshirt-310GSM-Cotton",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Pet Apparel"],
    subcategorySlugs: ["pet-apparel"],
    description: "Custom pet supplies — premium sublimation print, MOQ 50 pcs. 10 active SKUs.",
    tags: ["sublimation", "accessories", "pet-apparel", "custom-project", "polyester"],
  },
  {
    name: "Phone Case",
    slug: "accessories-phone-case",
    plate: "Accessories",
    process: "Sublimation",
    sku: "7",
    spu: "2ACPPG14",
    url: "https://www.yoycol.com/product_detail/2ACPPG14/iPhone-13-Series-Mobile-Phone-Case-Glass",
    fabricCount: 0,
    mainCategory: "hardgoods",
    mainCategoryLabel: "Hard Goods & Lifestyle",
    subcategories: ["Phone Cases"],
    subcategorySlugs: ["phone-cases"],
    description: "Custom phone case — premium sublimation print, MOQ 50 pcs. 7 active SKUs.",
    tags: ["sublimation", "accessories", "phone-cases", "hard-goods", "polyester"],
  },
  {
    name: "Tumbler & Mug",
    slug: "accessories-tumbler-and-mug",
    plate: "Accessories",
    process: "Sublimation",
    sku: "35",
    spu: "2AMTMB10",
    url: "https://www.yoycol.com/product_detail/2AMTMB10/20OZ-Straight-Cup-With-Sliding-Lid-Printed-in-USA",
    fabricCount: 0,
    mainCategory: "hardgoods",
    mainCategoryLabel: "Hard Goods & Lifestyle",
    subcategories: ["Mugs (wrap print)"],
    subcategorySlugs: ["mugs"],
    description: "Custom tumbler & mug — premium sublimation print, MOQ 50 pcs. 35 active SKUs.",
    tags: ["sublimation", "accessories", "mugs", "hard-goods", "polyester"],
  },
  {
    name: "Kids\' Shoes",
    slug: "footwear-kids-shoes",
    plate: "Footwear",
    process: "Sublimation",
    sku: "3",
    spu: "3SKFGB01",
    url: "https://www.yoycol.com/product_detail/3SKFGB01/Kids-Canvas-Shoes",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Shoe Uppers"],
    subcategorySlugs: ["shoe-uppers"],
    description: "Custom kids\' shoes — premium sublimation print, MOQ 50 pcs. 3 active SKUs.",
    tags: ["sublimation", "footwear", "shoe-uppers", "custom-project", "kids", "polyester"],
  },
  {
    name: "Men\'s Shoes",
    slug: "footwear-men-s-shoes",
    plate: "Footwear",
    process: "Sublimation",
    sku: "46",
    spu: "3MMSLQ02",
    url: "https://www.yoycol.com/product_detail/3MMSLQ02/Mens-Shock-Absorption-and-Non-Slip-Basketball-Shoes",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Shoe Uppers"],
    subcategorySlugs: ["shoe-uppers"],
    description: "Custom men\'s shoes — premium sublimation print, MOQ 50 pcs. 46 active SKUs.",
    tags: ["sublimation", "footwear", "shoe-uppers", "custom-project", "men", "polyester"],
  },
  {
    name: "Shoes",
    slug: "footwear-shoes",
    plate: "Footwear",
    process: "Sublimation",
    sku: "1",
    spu: "3SKSPA06",
    url: "https://www.yoycol.com/product_detail/3SKSPA06/The-palmix-Childrens-Hole-Shoes",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Shoe Uppers"],
    subcategorySlugs: ["shoe-uppers"],
    description: "Custom shoes — premium sublimation print, MOQ 50 pcs. 1 active SKUs.",
    tags: ["sublimation", "footwear", "shoe-uppers", "custom-project", "polyester"],
  },
  {
    name: "Socks",
    slug: "footwear-socks",
    plate: "Footwear",
    process: "Embroidery",
    sku: "3",
    spu: "4SSUCT01",
    url: "https://www.yoycol.com/product_detail/4SSUCT01/Embroidery-Sports-Cotton-Crew-Socks-Cotton",
    fabricCount: 0,
    mainCategory: "custom",
    mainCategoryLabel: "Custom Projects",
    subcategories: ["Anything else you imagine"],
    subcategorySlugs: ["custom-other"],
    description: "Custom socks — premium sublimation print, MOQ 50 pcs. 3 active SKUs.",
    tags: ["footwear", "custom-other", "custom-project"],
  },
];

export function productBySlug(slug: string): Product | undefined {
  return productTypes.find((p) => p.slug === slug);
}

export function productByTag(tag: string): Product[] {
  return productTypes.filter((p) => p.tags.includes(tag));
}