export type Product = {
  name: string;
  slug: string;
  plate: string;
  category: string;
  categoryDisplay: string;
  process: string;
  sku: string;
  spu: string;
  url: string;
  fabricCount: number;
  image: string;
  description: string;
  tags: string[];
};

export const productTypes: Product[] = [
  {
    name: "CrossFit Wear",
    slug: "crossfit-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "CrossFit",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom crossfit wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "crossfit", "polyester"],
  },
  {
    name: "Table Tennis Outfit",
    slug: "table-tennis-outfit",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "乒乓球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom table tennis outfit for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "table-tennis", "polyester"],
  },
  {
    name: "Transit & Transport Wear",
    slug: "transit-and-transport-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "交通运输",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom transit & transport wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "transit", "uniform", "polyester"],
  },
  {
    name: "Transit & Transport Wear可定制",
    slug: "transit-and-transport-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "交通运输",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom transit & transport wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "transit", "uniform", "polyester"],
  },
  {
    name: "Corporate & Promo Wear",
    slug: "corporate-and-promo-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "企业 / 团建",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom corporate & promo wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "corporate", "uniform", "polyester"],
  },
  {
    name: "Corporate & Promo Wear可定制",
    slug: "corporate-and-promo-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "企业 / 团建",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom corporate & promo wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "corporate", "uniform", "polyester"],
  },
  {
    name: "Bowling Shirt",
    slug: "bowling-shirt",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "保龄球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom bowling shirt for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "bowling", "shirt", "polyester"],
  },
  {
    name: "Gym Wear",
    slug: "gym-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "健身",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom gym wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "fitness", "polyester"],
  },
  {
    name: "Hockey Jersey",
    slug: "hockey-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "冰球",
    process: "Sublimation",
    sku: "12",
    spu: "3MTXLB56",
    url: "https://www.yoycol.com/product_detail/3MTXLB56/All-Over-Print-MenS-Half-Zip-Pullover-Sweatshirt",
    fabricCount: 2,
    image: "/products/cat-sport.webp",
    description: "Custom hockey jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 12 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "ice-hockey", "jersey", "polyester"],
  },
  {
    name: "Surf Wear",
    slug: "surf-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "冲浪",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom surf wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "surfing", "polyester"],
  },
  {
    name: "Medical & Healthcare Wear",
    slug: "medical-and-healthcare-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "医疗 / 健康",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 15,
    image: "/products/cat-industry.webp",
    description: "Custom medical & healthcare wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "medical", "uniform", "polyester"],
  },
  {
    name: "Medical & Healthcare Wear可定制",
    slug: "medical-and-healthcare-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "医疗 / 健康",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 15,
    image: "/products/cat-industry.webp",
    description: "Custom medical & healthcare wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "medical", "uniform", "polyester"],
  },
  {
    name: "Snowboard Wear",
    slug: "snowboard-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "单板滑雪",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom snowboard wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "snowboarding", "polyester"],
  },
  {
    name: "Cheer Wear",
    slug: "cheer-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "啦啦队",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom cheer wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "cheerleading", "polyester"],
  },
  {
    name: "Softball Jersey",
    slug: "softball-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "垒球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom softball jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "softball", "jersey", "polyester"],
  },
  {
    name: "Security Wear",
    slug: "security-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "安保 / 物业",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom security wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "security", "uniform", "polyester"],
  },
  {
    name: "Security Wear可定制",
    slug: "security-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "安保 / 物业",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom security wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "security", "uniform", "polyester"],
  },
  {
    name: "Construction Wear",
    slug: "construction-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "建筑 / 工程",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom construction wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "construction", "uniform", "polyester"],
  },
  {
    name: "Construction Wear可定制",
    slug: "construction-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "建筑 / 工程",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom construction wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "construction", "uniform", "polyester"],
  },
  {
    name: "Express & Logistics Wear",
    slug: "express-and-logistics-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "快递 / 物流",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom express & logistics wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "express-logistics", "uniform", "polyester"],
  },
  {
    name: "Express & Logistics Wear可定制",
    slug: "express-and-logistics-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "快递 / 物流",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom express & logistics wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "express-logistics", "uniform", "polyester"],
  },
  {
    name: "Boxing Gear",
    slug: "boxing-gear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "拳击",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom boxing gear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "boxing", "polyester"],
  },
  {
    name: "Volleyball Jersey",
    slug: "volleyball-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "排球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom volleyball jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "volleyball", "jersey", "polyester"],
  },
  {
    name: "Wrestling Gear",
    slug: "wrestling-gear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "摔跤",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom wrestling gear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "wrestling", "polyester"],
  },
  {
    name: "School & Education Wear",
    slug: "school-and-education-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "教育 / 校服",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom school & education wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "education", "uniform", "polyester"],
  },
  {
    name: "School & Education Wear可定制",
    slug: "school-and-education-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "教育 / 校服",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom school & education wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "education", "uniform", "polyester"],
  },
  {
    name: "Pilates Wear",
    slug: "pilates-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "普拉提",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom pilates wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "pilates", "polyester"],
  },
  {
    name: "Activewear",
    slug: "activewear",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "3",
    spu: "3MPHTU08",
    url: "https://www.yoycol.com/product_detail/3MPHTU08/All-Over-Print-Mens-long-Sleeve-T-Shirt-With-Dropped-Shoulders-Interlock",
    fabricCount: 3,
    image: "/products/cat-apparel.webp",
    description: "Activewear — custom sublimated activewear, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 3 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "polyester"],
  },
  {
    name: "Baby Bodysuit",
    slug: "baby-bodysuit",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "4",
    spu: "2KBBMB01",
    url: "https://www.yoycol.com/product_detail/2KBBMB01/Baby-Short-Sleeve-Onesie-Printed-in-USA-190GSM-Front-DTF",
    fabricCount: 0,
    image: "/products/cat-apparel.webp",
    description: "Baby Bodysuit — custom sublimated baby bodysuit, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 4 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "bodysuit", "kids", "polyester"],
  },
  {
    name: "Bodysuit",
    slug: "bodysuit",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "12",
    spu: "3WJMBX16",
    url: "https://www.yoycol.com/product_detail/3WJMBX16/All-Over-Print-Womens-Tank-Bodysuit",
    fabricCount: 1,
    image: "/products/cat-apparel.webp",
    description: "Bodysuit — custom sublimated bodysuit, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 12 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "bodysuit", "polyester"],
  },
  {
    name: "Coord Set",
    slug: "coord-set",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "34",
    spu: "3KCSZJ10",
    url: "https://www.yoycol.com/product_detail/3KCSZJ10/The-Plamix-All-Over-Print-Childrens-Shirt-With-Pocket-140GSM-Slub-Cotton",
    fabricCount: 4,
    image: "/products/cat-apparel.webp",
    description: "Coord Set — custom sublimated coord set, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 34 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "coord-set", "polyester"],
  },
  {
    name: "Dress",
    slug: "dress",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "50",
    spu: "3WBXGZ50",
    url: "https://www.yoycol.com/product_detail/3WBXGZ50/All-Over-Print-Womens-Tank-Vest-Dress",
    fabricCount: 4,
    image: "/products/cat-apparel.webp",
    description: "Dress — custom sublimated dress, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 50 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "dress", "women", "polyester"],
  },
  {
    name: "Hoodie",
    slug: "hoodie",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "397",
    spu: "2AHAYR15",
    url: "https://www.yoycol.com/product_detail/2AHAYR15/All-Over-Print-Womens-Rectangle-Scarf-170X45cm",
    fabricCount: 16,
    image: "/products/cat-apparel.webp",
    description: "Hoodie — custom sublimated hoodie, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 397 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "hoodie", "polyester"],
  },
  {
    name: "Jacket",
    slug: "jacket",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "84",
    spu: "2MHPJR90",
    url: "https://www.yoycol.com/product_detail/2MHPJR90/Mens-Fleece-Lined-Vintage-Wash-Zip-Hoodie-360GSM-DTF",
    fabricCount: 16,
    image: "/products/cat-apparel.webp",
    description: "Jacket — custom sublimated jacket, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 84 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "jacket", "polyester"],
  },
  {
    name: "Kids Sportswear",
    slug: "kids-sportswear",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "4",
    spu: "3KCSSY02",
    url: "https://www.yoycol.com/product_detail/3KCSSY02/All-Over-Print-Kids-Baseball-Jersey",
    fabricCount: 2,
    image: "/products/cat-apparel.webp",
    description: "Kids Sportswear — custom sublimated kids sportswear, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 4 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "kids", "polyester"],
  },
  {
    name: "Knitwear",
    slug: "knitwear",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "26",
    spu: "2MHPHR99",
    url: "https://www.yoycol.com/product_detail/2MHPHR99/Mens-Vintage-Crewneck-Knit-Sweater-285GSM-DTG",
    fabricCount: 5,
    image: "/products/cat-apparel.webp",
    description: "Knitwear — custom sublimated knitwear, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 26 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "knitwear", "polyester"],
  },
  {
    name: "Pants",
    slug: "pants",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "114",
    spu: "1WPXZY10",
    url: "https://www.yoycol.com/product_detail/1WPXZY10/All-Over-Print-Womens-High-Stretch-Tights",
    fabricCount: 13,
    image: "/products/cat-apparel.webp",
    description: "Pants — custom sublimated pants, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 114 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "pants", "polyester"],
  },
  {
    name: "Polo Shirt",
    slug: "polo-shirt",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "9",
    spu: "3KTXPL29",
    url: "https://www.yoycol.com/product_detail/3KTXPL29/All-Over-Print-Childrens-Lapel-Polo-Shirt-145GSM-Birdseye",
    fabricCount: 3,
    image: "/products/cat-apparel.webp",
    description: "Polo Shirt — custom sublimated polo shirt, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 9 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "shirt", "polo-shirt", "polyester"],
  },
  {
    name: "Romper & Jumpsuit",
    slug: "romper-and-jumpsuit",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "19",
    spu: "3MJMJH01",
    url: "https://www.yoycol.com/product_detail/3MJMJH01/All-Over-Print-Unisex-Thickened-Home-Jumpsuit",
    fabricCount: 4,
    image: "/products/cat-apparel.webp",
    description: "Romper & Jumpsuit — custom sublimated romper & jumpsuit, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 19 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "romper", "jumpsuit", "polyester"],
  },
  {
    name: "Shirt",
    slug: "shirt",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "103",
    spu: "2MHPDM39",
    url: "https://www.yoycol.com/product_detail/2MHPDM39/Unisex-Durable-Pullover-Sweatshirt-290GSM-DTG",
    fabricCount: 12,
    image: "/products/cat-apparel.webp",
    description: "Shirt — custom sublimated shirt, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 103 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "shirt", "polyester"],
  },
  {
    name: "Skirt",
    slug: "skirt",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "16",
    spu: "3CDDAQ01",
    url: "https://www.yoycol.com/product_detail/3CDDAQ01/All-Over-Print-Kids-Short-Sleeve-Dress",
    fabricCount: 2,
    image: "/products/cat-apparel.webp",
    description: "Skirt — custom sublimated skirt, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 16 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "skirt", "women", "polyester"],
  },
  {
    name: "Sleepwear & Underwear",
    slug: "sleepwear-and-underwear",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "62",
    spu: "2WUSMG97",
    url: "https://www.yoycol.com/product_detail/2WUSMG97/Womens-Seamless-Briefs-Printed-in-USA-180GSM-DTF",
    fabricCount: 10,
    image: "/products/cat-apparel.webp",
    description: "Sleepwear & Underwear — custom sublimated sleepwear & underwear, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 62 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "sleepwear", "underwear", "polyester"],
  },
  {
    name: "Sports Top",
    slug: "sports-top",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "7",
    spu: "3AHGYD02",
    url: "https://www.yoycol.com/product_detail/3AHGYD02/Sports-Square-Towel",
    fabricCount: 3,
    image: "/products/cat-apparel.webp",
    description: "Sports Top — custom sublimated sports top, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 7 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "polyester"],
  },
  {
    name: "Sweatshirt",
    slug: "sweatshirt",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "34",
    spu: "2MHPSA03",
    url: "https://www.yoycol.com/product_detail/2MHPSA03/Mens-Distressed-Vintage-Wash-Sweatshirt-360GSM-DTG",
    fabricCount: 5,
    image: "/products/cat-apparel.webp",
    description: "Sweatshirt — custom sublimated sweatshirt, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 34 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "t-shirt", "shirt", "sweatshirt", "polyester"],
  },
  {
    name: "T-Shirt",
    slug: "t-shirt",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "135",
    spu: "2KTXDM69",
    url: "https://www.yoycol.com/product_detail/2KTXDM69/Childrens-T-Shirts-Printed-in-USA-Gildan-64000B-DTG",
    fabricCount: 14,
    image: "/products/cat-apparel.webp",
    description: "T-Shirt — custom sublimated t-shirt, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 135 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "t-shirt", "shirt", "polyester"],
  },
  {
    name: "Tank Top & Camis",
    slug: "tank-top-and-camis",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "61",
    spu: "2MBXMA09",
    url: "https://www.yoycol.com/product_detail/2MBXMA09/Mens-Loose-Sleeveless-Hoodie-320GSM-DTF",
    fabricCount: 7,
    image: "/products/cat-apparel.webp",
    description: "Tank Top & Camis — custom sublimated tank top & camis, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 61 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "tank-top", "camisole", "polyester"],
  },
  {
    name: "Winter Wear",
    slug: "winter-wear",
    plate: "All-Over Print",
    category: "apparel-type",
    categoryDisplay: "服装品种",
    process: "Sublimation",
    sku: "4",
    spu: "3MHZDM41",
    url: "https://www.yoycol.com/product_detail/3MHZDM41/All-Over-Print-Mens-Half-Zip-Pullover",
    fabricCount: 3,
    image: "/products/cat-apparel.webp",
    description: "Winter Wear — custom sublimated winter wear, cut and sewn in our Yiwu factory. Full-color all-over print, MOQ 50 pcs, sample in 5 days. 4 active SKUs.",
    tags: ["all-over-print", "apparel-type", "sublimation", "vivid-color", "polyester"],
  },
  {
    name: "Cricket Outfit",
    slug: "cricket-outfit",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "板球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom cricket outfit for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "cricket", "polyester"],
  },
  {
    name: "Baseball Jersey",
    slug: "baseball-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "棒球",
    process: "Sublimation",
    sku: "8",
    spu: "2AMSMG90",
    url: "https://www.yoycol.com/product_detail/2AMSMG90/Adult-Solid-Color-Mesh-Baseball-Cap-Printed-in-USA",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom baseball jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 8 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "baseball", "jersey", "polyester"],
  },
  {
    name: "Rugby Jersey",
    slug: "rugby-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "橄榄球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom rugby jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "rugby", "jersey", "polyester"],
  },
  {
    name: "Martial Arts Gear",
    slug: "martial-arts-gear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "武术",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom martial arts gear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "martial-arts", "polyester"],
  },
  {
    name: "Beach Sports",
    slug: "beach-sports",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "沙滩运动",
    process: "Sublimation",
    sku: "4",
    spu: "2HBTSJ19",
    url: "https://www.yoycol.com/product_detail/2HBTSJ19/Adult-Beach-Towel-Printed-in-Canada-320GSM",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom beach sports for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 4 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "beach-sports", "polyester"],
  },
  {
    name: "Swimwear",
    slug: "swimwear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "游泳",
    process: "Sublimation",
    sku: "28",
    spu: "3KYYOP05",
    url: "https://www.yoycol.com/product_detail/3KYYOP05/All-Over-Print-Girls-Sleeveless-One-Piece-Swimsuit",
    fabricCount: 1,
    image: "/products/cat-sport.webp",
    description: "Custom swimwear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 28 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "swimming", "polyester"],
  },
  {
    name: "Skating Wear",
    slug: "skating-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "滑冰",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom skating wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "ice-skating", "polyester"],
  },
  {
    name: "Skate Wear",
    slug: "skate-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "滑板",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom skate wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "skateboarding", "polyester"],
  },
  {
    name: "Ski Wear",
    slug: "ski-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "滑雪",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom ski wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "skiing", "polyester"],
  },
  {
    name: "Dive Wear",
    slug: "dive-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "潜水",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom dive wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "diving", "polyester"],
  },
  {
    name: "AFL Jersey",
    slug: "afl-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "澳式足球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom afl jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "afl", "jersey", "polyester"],
  },
  {
    name: "Yoga Wear",
    slug: "yoga-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "瑜伽",
    process: "Sublimation",
    sku: "26",
    spu: "3CP",
    url: "https://www.yoycol.com/product_detail/3CP/All-Over-Print-Casual-Leggings",
    fabricCount: 2,
    image: "/products/cat-sport.webp",
    description: "Custom yoga wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 26 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "yoga", "polyester"],
  },
  {
    name: "Athletics Wear",
    slug: "athletics-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "田径",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom athletics wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "athletics", "polyester"],
  },
  {
    name: "Esports Jersey",
    slug: "esports-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "电竞",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom esports jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "esports", "jersey", "polyester"],
  },
  {
    name: "Basketball Jersey",
    slug: "basketball-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "篮球",
    process: "Sublimation",
    sku: "11",
    spu: "3MBXVL01",
    url: "https://www.yoycol.com/product_detail/3MBXVL01/All-Over-Print-Mens-V-neck-Tank-Top",
    fabricCount: 1,
    image: "/products/cat-sport.webp",
    description: "Custom basketball jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 11 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "basketball", "jersey", "polyester"],
  },
  {
    name: "Netball Jersey",
    slug: "netball-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "篮网球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom netball jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "netball", "jersey", "polyester"],
  },
  {
    name: "MMA Gear",
    slug: "mma-gear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "综合格斗",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom mma gear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "mma", "polyester"],
  },
  {
    name: "Tennis Outfit",
    slug: "tennis-outfit",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "网球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom tennis outfit for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "tennis", "polyester"],
  },
  {
    name: "Football Jersey",
    slug: "football-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "美式橄榄球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom football jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "american-football", "jersey", "polyester"],
  },
  {
    name: "Badminton Outfit",
    slug: "badminton-outfit",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "羽毛球",
    process: "Sublimation",
    sku: "6",
    spu: "3MBXGT28",
    url: "https://www.yoycol.com/product_detail/3MBXGT28/All-Over-Print-Mens-O-neck-Tank-Top-210GSM",
    fabricCount: 3,
    image: "/products/cat-sport.webp",
    description: "Custom badminton outfit for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 6 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "badminton", "polyester"],
  },
  {
    name: "Dance Wear",
    slug: "dance-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "舞蹈",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom dance wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "dance", "polyester"],
  },
  {
    name: "Soccer Jersey",
    slug: "soccer-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "足球",
    process: "Sublimation",
    sku: "8",
    spu: "3MPXDK57",
    url: "https://www.yoycol.com/product_detail/3MPXDK57/All-Over-Print-Mens-Pocket-Customizable-Shorts",
    fabricCount: 3,
    image: "/products/cat-sport.webp",
    description: "Custom soccer jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 8 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "soccer", "jersey", "polyester"],
  },
  {
    name: "Running Wear",
    slug: "running-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "跑步",
    process: "Sublimation",
    sku: "14",
    spu: "3MBXGT27",
    url: "https://www.yoycol.com/product_detail/3MBXGT27/All-Over-Print-Mens-Sports-Vest",
    fabricCount: 2,
    image: "/products/cat-sport.webp",
    description: "Custom running wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 14 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "running", "polyester"],
  },
  {
    name: "Fishing Shirt",
    slug: "fishing-shirt",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "钓鱼",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom fishing shirt for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "fishing", "shirt", "polyester"],
  },
  {
    name: "Triathlon Wear",
    slug: "triathlon-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "铁人三项",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom triathlon wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "triathlon", "polyester"],
  },
  {
    name: "Lacrosse Jersey",
    slug: "lacrosse-jersey",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "长曲棍球",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 0,
    image: "/products/cat-sport.webp",
    description: "Custom lacrosse jersey for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "lacrosse", "jersey", "polyester"],
  },
  {
    name: "Retail Wear",
    slug: "retail-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "零售 / 商超",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom retail wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "retail", "uniform", "polyester"],
  },
  {
    name: "Retail Wear可定制",
    slug: "retail-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "零售 / 商超",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom retail wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "retail", "uniform", "polyester"],
  },
  {
    name: "Hospitality & F&B Wear",
    slug: "hospitality-and-fandb-wear",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "餐饮 / 酒店",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom hospitality & f&b wear for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "hospitality", "uniform", "polyester"],
  },
  {
    name: "Hospitality & F&B Wear可定制",
    slug: "hospitality-and-fandb-wear可定制",
    plate: "All-Over Print",
    category: "industry",
    categoryDisplay: "餐饮 / 酒店",
    process: "Sublimation",
    sku: "custom",
    spu: "—",
    url: "",
    fabricCount: 16,
    image: "/products/cat-industry.webp",
    description: "Custom hospitality & f&b wear可定制 for industry teams and uniform programs. Durable fabrics, professional finish, bulk pricing available.",
    tags: ["all-over-print", "industry", "sublimation", "vivid-color", "hospitality", "uniform", "polyester"],
  },
  {
    name: "Cycling Wear",
    slug: "cycling-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "骑行",
    process: "Sublimation",
    sku: "12",
    spu: "3MTXUB79",
    url: "https://www.yoycol.com/product_detail/3MTXUB79/All-Over-Print-Mens-Sun-Protection-Hooded-Sport-Top",
    fabricCount: 2,
    image: "/products/cat-sport.webp",
    description: "Custom cycling wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 12 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "cycling", "polyester"],
  },
  {
    name: "Golf Wear",
    slug: "golf-wear",
    plate: "All-Over Print",
    category: "sport",
    categoryDisplay: "高尔夫",
    process: "Sublimation",
    sku: "47",
    spu: "3KCSFH01",
    url: "https://www.yoycol.com/product_detail/3KCSFH01/All-Over-Print-Teenage-Polo-Collar-Jersey",
    fabricCount: 8,
    image: "/products/cat-sport.webp",
    description: "Custom golf wear for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 47 active SKUs.",
    tags: ["all-over-print", "sport", "sublimation", "vivid-color", "golf", "polyester"],
  },
  {
    name: "Baby Bodysuit",
    slug: "blank-baby-bodysuit",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF",
    sku: "3",
    spu: "2KBBMB01",
    url: "https://www.yoycol.com/product_detail/2KBBMB01/Baby-Short-Sleeve-Onesie-Printed-in-USA-190GSM-Front-DTF",
    fabricCount: 2,
    image: "/products/cat-blank.webp",
    description: "Custom baby bodysuit on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 3 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "cotton-friendly", "dark-friendly", "bodysuit", "kids", "cotton"],
  },
  {
    name: "Hoodie",
    slug: "blank-hoodie",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF",
    sku: "4",
    spu: "2MHPDM73",
    url: "https://www.yoycol.com/product_detail/2MHPDM73/Unisex-Pullover-Hoodie-with-Micro-Fleece-Lining-DTF",
    fabricCount: 16,
    image: "/products/cat-blank.webp",
    description: "Custom hoodie on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 4 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "cotton-friendly", "dark-friendly", "hoodie", "cotton"],
  },
  {
    name: "Pants",
    slug: "blank-pants",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF",
    sku: "1",
    spu: "2MPXMB02",
    url: "https://www.yoycol.com/product_detail/2MPXMB02/Mens-Casual-Shorts-Printed-in-USA-290GSM-Front-DTF",
    fabricCount: 6,
    image: "/products/cat-blank.webp",
    description: "Custom pants on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 1 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "cotton-friendly", "dark-friendly", "pants", "cotton"],
  },
  {
    name: "Set",
    slug: "blank-set",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF",
    sku: "1",
    spu: "3WSTLL37",
    url: "https://www.yoycol.com/product_detail/3WSTLL37/Womens-Tracksuit-With-Fleece-DTF",
    fabricCount: 0,
    image: "/products/cat-blank.webp",
    description: "Custom set on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 1 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "cotton-friendly", "dark-friendly", "cotton"],
  },
  {
    name: "Shirt",
    slug: "blank-shirt",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF/DTG",
    sku: "12",
    spu: "2MTXMB06",
    url: "https://www.yoycol.com/product_detail/2MTXMB06/Mens-Long-Sleeve-T-Shirt-Printed-in-USA-180GSM-Double-DTF",
    fabricCount: 10,
    image: "/products/cat-blank.webp",
    description: "Custom shirt on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 12 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "dtg", "cotton-friendly", "shirt", "cotton"],
  },
  {
    name: "Sweatshirt",
    slug: "blank-sweatshirt",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF",
    sku: "5",
    spu: "2MWYYL01",
    url: "https://www.yoycol.com/product_detail/2MWYYL01/Versatile-Mens-Polyester-Fleece-Sweatshirt-DTF",
    fabricCount: 5,
    image: "/products/cat-blank.webp",
    description: "Custom sweatshirt on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 5 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "cotton-friendly", "dark-friendly", "t-shirt", "shirt", "sweatshirt", "cotton"],
  },
  {
    name: "T-Shirt",
    slug: "blank-t-shirt",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF/DTG",
    sku: "13",
    spu: "2KTXMD71",
    url: "https://www.yoycol.com/product_detail/2KTXMD71/Youth-T-shirt-Printed-in-USA-180GSM-Front-Back-DTF",
    fabricCount: 10,
    image: "/products/cat-blank.webp",
    description: "Custom t-shirt on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 13 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "dtg", "cotton-friendly", "t-shirt", "shirt", "cotton"],
  },
  {
    name: "Tank Top",
    slug: "blank-tank-top",
    plate: "Blank",
    category: "basic-custom",
    categoryDisplay: "基础定制",
    process: "DTF",
    sku: "3",
    spu: "2MBXMD71",
    url: "https://www.yoycol.com/product_detail/2MBXMD71/Washed-Cotton-Sleeveless-T-Shirt-Printed-in-USA-210GSM-Cotton-Double-sided-DTF",
    fabricCount: 0,
    image: "/products/cat-blank.webp",
    description: "Custom tank top on blank garments via DTG/DTF. Perfect for fashion brands, small-batch runs, and retail. 3 active SKUs.",
    tags: ["blank-garment", "basic-custom", "dtf", "cotton-friendly", "dark-friendly", "tank-top", "cotton"],
  },
  {
    name: "Polo Shirt",
    slug: "blank-polo-shirt",
    plate: "Blank",
    category: "sport",
    categoryDisplay: "高尔夫",
    process: "DTF/DTG",
    sku: "6",
    spu: "2MTXCM57",
    url: "https://www.yoycol.com/product_detail/2MTXCM57/Adult-Polo-Jersey-Sport-Shirt-Printed-in-USA-Gildan8800-DTF-Front",
    fabricCount: 3,
    image: "/products/cat-sport.webp",
    description: "Custom polo shirt for teams, clubs, and events. All-over sublimation, breathable fabric, full-color print, MOQ 50 pcs. 6 active SKUs.",
    tags: ["blank-garment", "sport", "dtf", "dtg", "cotton-friendly", "golf", "shirt", "polo-shirt", "cotton"],
  },
  {
    name: "Blanket & Bedding",
    slug: "home-blanket-and-bedding",
    plate: "Home & Living",
    category: "home-living",
    categoryDisplay: "家居家纺",
    process: "Sublimation",
    sku: "31",
    spu: "2AAOWO9",
    url: "https://www.yoycol.com/product_detail/2AAOWO9/Personalized-Plush-Hug-Doll-Pillow",
    fabricCount: 0,
    image: "/products/cat-home.webp",
    description: "Custom blanket & bedding — home textile decoration. Soft, vivid sublimation, machine washable, custom sizes available. 31 active SKUs.",
    tags: ["home-living", "sublimation", "all-over-print", "vivid-color", "blanket", "polyester"],
  },
  {
    name: "Desk & Stationery",
    slug: "home-desk-and-stationery",
    plate: "Home & Living",
    category: "home-living",
    categoryDisplay: "家居家纺",
    process: "Sublimation",
    sku: "5",
    spu: "2HKKZB08",
    url: "https://www.yoycol.com/product_detail/2HKKZB08/Single-Sided-Printed-Prayer-Journal",
    fabricCount: 0,
    image: "/products/cat-home.webp",
    description: "Custom desk & stationery — home textile decoration. Soft, vivid sublimation, machine washable, custom sizes available. 5 active SKUs.",
    tags: ["home-living", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Kitchen & Apron",
    slug: "home-kitchen-and-apron",
    plate: "Home & Living",
    category: "home-living",
    categoryDisplay: "家居家纺",
    process: "Sublimation",
    sku: "7",
    spu: "2HKAWQ05",
    url: "https://www.yoycol.com/product_detail/2HKAWQ05/Adjustable-Apron-With-White-Strap",
    fabricCount: 0,
    image: "/products/cat-home.webp",
    description: "Custom kitchen & apron — home textile decoration. Soft, vivid sublimation, machine washable, custom sizes available. 7 active SKUs.",
    tags: ["home-living", "sublimation", "all-over-print", "vivid-color", "apron", "polyester"],
  },
  {
    name: "Outdoor & Garden",
    slug: "home-outdoor-and-garden",
    plate: "Home & Living",
    category: "home-living",
    categoryDisplay: "家居家纺",
    process: "Sublimation",
    sku: "39",
    spu: "2AAOFT01",
    url: "https://www.yoycol.com/product_detail/2AAOFT01/Halloween-Windsock",
    fabricCount: 0,
    image: "/products/cat-home.webp",
    description: "Custom outdoor & garden — home textile decoration. Soft, vivid sublimation, machine washable, custom sizes available. 39 active SKUs.",
    tags: ["home-living", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Towel",
    slug: "home-towel",
    plate: "Home & Living",
    category: "home-living",
    categoryDisplay: "家居家纺",
    process: "Sublimation",
    sku: "14",
    spu: "2HBTSJ19",
    url: "https://www.yoycol.com/product_detail/2HBTSJ19/Adult-Beach-Towel-Printed-in-Canada-320GSM",
    fabricCount: 0,
    image: "/products/cat-home.webp",
    description: "Custom towel — home textile decoration. Soft, vivid sublimation, machine washable, custom sizes available. 14 active SKUs.",
    tags: ["home-living", "sublimation", "all-over-print", "vivid-color", "towel", "polyester"],
  },
  {
    name: "Wall Art",
    slug: "home-wall-art",
    plate: "Home & Living",
    category: "home-living",
    categoryDisplay: "家居家纺",
    process: "Sublimation",
    sku: "64",
    spu: "1PCP",
    url: "https://www.yoycol.com/product_detail/1PCP/Frameless-Single-Mural",
    fabricCount: 0,
    image: "/products/cat-home.webp",
    description: "Custom wall art — home textile decoration. Soft, vivid sublimation, machine washable, custom sizes available. 64 active SKUs.",
    tags: ["home-living", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Bag",
    slug: "accessories-bag",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "49",
    spu: "2ABBDJ69",
    url: "https://www.yoycol.com/product_detail/2ABBDJ69/Minimalist-Square-Crossbody-Bucket-Bag",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom bag — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 49 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "bag", "polyester"],
  },
  {
    name: "Car Accessories",
    slug: "accessories-car-accessories",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "12",
    spu: "2AAOMG70",
    url: "https://www.yoycol.com/product_detail/2AAOMG70/Car-Aluminum-License-Plate-Printed-in-USA",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom car accessories — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 12 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Face Mask",
    slug: "accessories-face-mask",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "3",
    spu: "320KZ",
    url: "https://www.yoycol.com/product_detail/320KZ/All-Over-Print-Face-Mask-with-Adjustable-Ear-Loops",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom face mask — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 3 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Hat & Cap",
    slug: "accessories-hat-and-cap",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "36",
    spu: "2AAOYF03",
    url: "https://www.yoycol.com/product_detail/2AAOYF03/Bucket-Hat",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom hat & cap — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 36 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "cap", "hat", "polyester"],
  },
  {
    name: "Jewelry",
    slug: "accessories-jewelry",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "3",
    spu: "2AJBSS05",
    url: "https://www.yoycol.com/product_detail/2AJBSS05/Mens-Fashion-Belt",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom jewelry — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 3 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Pet Supplies",
    slug: "accessories-pet-supplies",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "10",
    spu: "3AHPDG01",
    url: "https://www.yoycol.com/product_detail/3AHPDG01/All-Over-Print-Hooded-Sweatshirt-310GSM-Cotton",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom pet supplies — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 10 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Phone Case",
    slug: "accessories-phone-case",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "7",
    spu: "2ACPPG14",
    url: "https://www.yoycol.com/product_detail/2ACPPG14/iPhone-13-Series-Mobile-Phone-Case-Glass",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom phone case — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 7 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "polyester"],
  },
  {
    name: "Tumbler & Mug",
    slug: "accessories-tumbler-and-mug",
    plate: "Accessories",
    category: "accessory",
    categoryDisplay: "配件周边",
    process: "Sublimation",
    sku: "35",
    spu: "2AMTMB10",
    url: "https://www.yoycol.com/product_detail/2AMTMB10/20OZ-Straight-Cup-With-Sliding-Lid-Printed-in-USA",
    fabricCount: 0,
    image: "/products/cat-accessory.webp",
    description: "Custom tumbler & mug — perfect for events, brand merch, and promotional campaigns. Full-color print, low MOQ. 35 active SKUs.",
    tags: ["accessory", "sublimation", "all-over-print", "vivid-color", "mug", "polyester"],
  },
  {
    name: "Kids\' Shoes",
    slug: "footwear-kids-shoes",
    plate: "Footwear",
    category: "footwear",
    categoryDisplay: "鞋履",
    process: "Sublimation",
    sku: "3",
    spu: "3SKFGB01",
    url: "https://www.yoycol.com/product_detail/3SKFGB01/Kids-Canvas-Shoes",
    fabricCount: 0,
    image: "/products/cat-footwear.webp",
    description: "Custom kids\' shoes — full-surface sublimation for shoes, socks, and footwear accessories. 3 active SKUs.",
    tags: ["footwear", "sublimation", "all-over-print", "vivid-color", "shoe", "kids", "polyester"],
  },
  {
    name: "Men\'s Shoes",
    slug: "footwear-men-s-shoes",
    plate: "Footwear",
    category: "footwear",
    categoryDisplay: "鞋履",
    process: "Sublimation",
    sku: "46",
    spu: "3MMSLQ02",
    url: "https://www.yoycol.com/product_detail/3MMSLQ02/Mens-Shock-Absorption-and-Non-Slip-Basketball-Shoes",
    fabricCount: 0,
    image: "/products/cat-footwear.webp",
    description: "Custom men\'s shoes — full-surface sublimation for shoes, socks, and footwear accessories. 46 active SKUs.",
    tags: ["footwear", "sublimation", "all-over-print", "vivid-color", "shoe", "men", "polyester"],
  },
  {
    name: "Shoes",
    slug: "footwear-shoes",
    plate: "Footwear",
    category: "footwear",
    categoryDisplay: "鞋履",
    process: "Sublimation",
    sku: "1",
    spu: "3SKSPA06",
    url: "https://www.yoycol.com/product_detail/3SKSPA06/The-palmix-Childrens-Hole-Shoes",
    fabricCount: 0,
    image: "/products/cat-footwear.webp",
    description: "Custom shoes — full-surface sublimation for shoes, socks, and footwear accessories. 1 active SKUs.",
    tags: ["footwear", "sublimation", "all-over-print", "vivid-color", "shoe", "polyester"],
  },
  {
    name: "Socks",
    slug: "footwear-socks",
    plate: "Footwear",
    category: "footwear",
    categoryDisplay: "鞋履",
    process: "Embroidery",
    sku: "3",
    spu: "4SSUCT01",
    url: "https://www.yoycol.com/product_detail/4SSUCT01/Embroidery-Sports-Cotton-Crew-Socks-Cotton",
    fabricCount: 0,
    image: "/products/cat-footwear.webp",
    description: "Custom socks — full-surface sublimation for shoes, socks, and footwear accessories. 3 active SKUs.",
    tags: ["footwear", "sublimation", "sock"],
  },
];

export const productCategoryDisplay: Record<string, string> = {
  "apparel-type": "Apparel Type",
  "sport": "Sport",
  "industry": "Industry",
  "basic-custom": "Basic Custom",
  "home-living": "Home & Living",
  "accessory": "Accessory",
  "footwear": "Footwear",
};

export const productAllTags = [
  "accessory",
  "afl",
  "all-over-print",
  "american-football",
  "apparel-type",
  "apron",
  "athletics",
  "badminton",
  "bag",
  "baseball",
  "basic-custom",
  "basketball",
  "beach-sports",
  "blank-garment",
  "blanket",
  "bodysuit",
  "bowling",
  "boxing",
  "camisole",
  "cap",
  "cheerleading",
  "construction",
  "coord-set",
  "corporate",
  "cotton",
  "cotton-friendly",
  "cricket",
  "crossfit",
  "cycling",
  "dance",
  "dark-friendly",
  "diving",
  "dress",
  "dtf",
  "dtg",
  "education",
  "esports",
  "express-logistics",
  "fishing",
  "fitness",
  "footwear",
  "golf",
  "hat",
  "home-living",
  "hoodie",
  "hospitality",
  "ice-hockey",
  "ice-skating",
  "industry",
  "jacket",
  "jersey",
  "jumpsuit",
  "kids",
  "knitwear",
  "lacrosse",
  "martial-arts",
  "medical",
  "men",
  "mma",
  "mug",
  "netball",
  "pants",
  "pilates",
  "polo-shirt",
  "polyester",
  "retail",
  "romper",
  "rugby",
  "running",
  "security",
  "shirt",
  "shoe",
  "skateboarding",
  "skiing",
  "skirt",
  "sleepwear",
  "snowboarding",
  "soccer",
  "sock",
  "softball",
  "sport",
  "sublimation",
  "surfing",
  "sweatshirt",
  "swimming",
  "t-shirt",
  "table-tennis",
  "tank-top",
  "tennis",
  "towel",
  "transit",
  "triathlon",
  "underwear",
  "uniform",
  "vivid-color",
  "volleyball",
  "women",
  "wrestling",
  "yoga",
];

export function productBySlug(slug: string): Product | undefined {
  return productTypes.find((p) => p.slug === slug);
}

export function productByTag(tag: string): Product[] {
  return productTypes.filter((p) => p.tags.includes(tag));
}